### ISSUE TITLE
1.99.12 - BulbTracer2 - "Save type" DropDown

### ISSUE THREAD

**Issue by Amanito** [thargor6/mb3d#10]
First of all - thank you for your work !!!!
After choosing a "Output file" destination via the button, the dropdown to choose filetypes doesn't show the new features anymore but only:
Mesh (*.obj)
Tracedata (*.btracer2)
Thanks a lot, Andreas

**Comment by thargor6** [comment]
Thanks for your feedback and for reporting this! It is fixed now (you might just download the *.zip again). Cheers!
