### ISSUE TITLE
no Mandelbulb3D.exe in zip?

### ISSUE THREAD

**Issue by CoreyCorza** [thargor6/mb3d#15]
Extracted the contents of the zip file but there doesn't appear to be any .exe file of which the instructions refer to.
Ive checked to make sure windows defender isn't flagging it or something. And checked through the other various folders.

**Comment by WAUthethird** [comment]
If you downloaded directly from the Github, you only downloaded the source code.

You'll need to download a release from the maintainer's website.

**Comment by thargor6** [comment]
exactly like WAUthethird said, here is the link to the mentioned website: https://mb3d.overwhale.com/

**Comment by CoreyCorza** [comment]
Ahh I see. Thanks
