### ISSUE TITLE
Optimizing Normals of point cloud 10x faster

### ISSUE THREAD

**Issue by ZoomDomain** [thargor6/mb3d#3]
I have found complex vector maths to find the vertex normals. things like crossproduct use a _square root_ which requires the same processing as about 50 compare functions. I believe this entire function TRayCaster.CalculateNormal can be 9x faster, it is consuming 90 percent of the time taken to make a meshable point cloud. 

If i could read pascal, I would change that function with something very simple... Vertex and Normal calculated in the same loop. to get normals very fast, ready 6 (array stored) formula values for +x-x  +y-y   +z-y, and abort the loop as soon as you have found an empty space in the immediate periphery. the nromal will be straight, but it will point outside the surface and programs can use that to mesh with. 

so, vertex is averaged between the 6 neighbor values of inside and outside, and normal points simply towards the outside from the inside , using table normals which are assigned 6 possible options. else the 6 neighbor check can start with 0,0,0 normals and replace the 0's with 1's untill you get all combinations of 000 to 111  -111 in a Vector3. 

In meshlab afterwards, all the vertices stay in the same place and are anti-aliased because all points along a segment come from 2 isovalues/2... 

You can optimize the precission massively by only adding to vertex list, vertices and normals that have more than 1 empty neighbor cube from the loop, so you randomly throw out 90% vertices with (0.0.1)or(0,-1,0) type normals, less variety /flat areas get decimated by 90 percent, and high convolution areas have 100 percent of data save as a point cloud. 

That's an info/data compression method that you can adjust from 0-90 percent, to plot 4000x4000x4000 point clouds in 30 minutes at 0-90 percent optional compression gradient. 

 TDVectorMath.Assign(@Axis, @Direction);
  TDVectorMath.Normalize(@Axis);
  TDVectorMath.NonParallel(@A, @Axis);
  TDVectorMath.CrossProduct(@A, @Axis, @T[0]);
  TDVectorMath.Normalize(@T[0]);

**Comment by thargor6** [comment]
I'm sure it can be made faster, but speed was never the point. What you
talk about is premature optimization, which is an anti-pattern. First, get
it right/done, then optimize it. It is far away from being done ;-)

Cheers!

2017-11-24 15:43 GMT+01:00 ZoomDomain <notifications@github.com>:
