### ISSUE TITLE
conversion to Lazarus

### ISSUE THREAD

**Issue by ghost** [thargor6/mb3d#7]
REF http://wiki.freepascal.org/Delphi_Converter_in_Lazarus
REF http://www.fractalforums.com/mandelbulb-3d/mandelbulb3d-source-code-t21204/
mb3d currently compiled in delphi (asume Delphi XE6)

First issue encountered is Vcl.Themes Vcl.Styles

**Comment by thargor6** [comment]
I don't think there will be much success in converting this project to Lazarus. Most of the core is written in ASM, I don't think this will translate well to Lazarus. 
But maybe I am wrong, had no look at Lazarus for about 1 year.

**Comment by ghost** [comment]
The ASM is no issue, the problems exist within the Delphi specific libraries. (Vcl.Themes Vcl.Styles). I will see if it’s possible to find a drop in replacement with the current codebase.

**Comment by thargor6** [comment]
OK, probably VCl.Themes and Vcl.Styles could be removed without too much impact and changes.
