### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by WAUthethird** [thargor6/mb3d#8]
So...
Why exactly isn't there a readme?
Would it get in the way when you compile or something?

**Comment by Atavic** [comment]
Most probably this is just a dev repo, most discussions/info are on other places:

>http://www.andreas-maschke.com/?page_id=4607
http://www.fractalforums.com/3d-fractal-generation/

**Comment by thargor6** [comment]
What exactly are you missing?

**Comment by WAUthethird** [comment]
Even though this is a development repository, most developers provide info on how to build, what this project is, etc etc. in the readme.

I'm well informed on what MB3D is, it'd just be helpful to know how to build it; things like that.
Also, a bit of info on running it on operating systems other than Windows would be helpful; most instructions on how to do this are pretty vague.

I understand this isn't technically _required,_ but I think having a readme would be quite beneficial to this repository and the users that view it.

Thanks!

**Comment by WAUthethird** [comment]
Ah well, I guess it doesn't matter that much.
